name       = "scc"
repository = "https://github.com/boyter/scc"
args       = ["--format", "json", "{file}"]
explain-args      = ["-t", "--no-cocomo", "-f", "csv", "{file}"]
explain-keep-from = "line "

[acquisition]
channel = "github-release-asset"
name    = "boyter/scc"

[dialect.default]
args = []

[dialect.default.read]
each     = "[]"
lines    = "Lines"
code     = "Code"
comments = "Comment"
blanks   = "Blank"
