name       = "tokei"
repository = "https://github.com/XAMPPRocky/tokei"
output     = "tokei-json"
args       = ["--output", "json", "{file}"]

[acquisition]
channel = "crates-io"
name    = "tokei"
version = "15.0.0"

[dialect.default]
args = []
